# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haq/Code/CLI/loxs/xssmap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haq/Code/CLI/loxs/xssmap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haq/Code/CLI/loxs/xssmap/CMakeFiles /home/haq/Code/CLI/loxs/xssmap//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haq/Code/CLI/loxs/xssmap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xssmap

# Build rule for target.
xssmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xssmap
.PHONY : xssmap

# fast build rule for target.
xssmap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/build
.PHONY : xssmap/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

benchmark.o: benchmark.c.o
.PHONY : benchmark.o

# target to build an object file
benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.o
.PHONY : benchmark.c.o

benchmark.i: benchmark.c.i
.PHONY : benchmark.i

# target to preprocess a source file
benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.i
.PHONY : benchmark.c.i

benchmark.s: benchmark.c.s
.PHONY : benchmark.s

# target to generate assembly for a file
benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.c.s
.PHONY : benchmark.c.s

src/http.o: src/http.c.o
.PHONY : src/http.o

# target to build an object file
src/http.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/http.c.o
.PHONY : src/http.c.o

src/http.i: src/http.c.i
.PHONY : src/http.i

# target to preprocess a source file
src/http.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/http.c.i
.PHONY : src/http.c.i

src/http.s: src/http.c.s
.PHONY : src/http.s

# target to generate assembly for a file
src/http.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/http.c.s
.PHONY : src/http.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/main.c.s
.PHONY : src/main.c.s

src/scanner.o: src/scanner.c.o
.PHONY : src/scanner.o

# target to build an object file
src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/scanner.c.o
.PHONY : src/scanner.c.o

src/scanner.i: src/scanner.c.i
.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/scanner.c.i
.PHONY : src/scanner.c.i

src/scanner.s: src/scanner.c.s
.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/scanner.c.s
.PHONY : src/scanner.c.s

src/techniques/advanced.o: src/techniques/advanced.c.o
.PHONY : src/techniques/advanced.o

# target to build an object file
src/techniques/advanced.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/advanced.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/advanced.c.o
.PHONY : src/techniques/advanced.c.o

src/techniques/advanced.i: src/techniques/advanced.c.i
.PHONY : src/techniques/advanced.i

# target to preprocess a source file
src/techniques/advanced.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/advanced.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/advanced.c.i
.PHONY : src/techniques/advanced.c.i

src/techniques/advanced.s: src/techniques/advanced.c.s
.PHONY : src/techniques/advanced.s

# target to generate assembly for a file
src/techniques/advanced.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/advanced.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/advanced.c.s
.PHONY : src/techniques/advanced.c.s

src/techniques/attrbreak.o: src/techniques/attrbreak.c.o
.PHONY : src/techniques/attrbreak.o

# target to build an object file
src/techniques/attrbreak.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/attrbreak.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/attrbreak.c.o
.PHONY : src/techniques/attrbreak.c.o

src/techniques/attrbreak.i: src/techniques/attrbreak.c.i
.PHONY : src/techniques/attrbreak.i

# target to preprocess a source file
src/techniques/attrbreak.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/attrbreak.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/attrbreak.c.i
.PHONY : src/techniques/attrbreak.c.i

src/techniques/attrbreak.s: src/techniques/attrbreak.c.s
.PHONY : src/techniques/attrbreak.s

# target to generate assembly for a file
src/techniques/attrbreak.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/attrbreak.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/attrbreak.c.s
.PHONY : src/techniques/attrbreak.c.s

src/techniques/dombreak.o: src/techniques/dombreak.c.o
.PHONY : src/techniques/dombreak.o

# target to build an object file
src/techniques/dombreak.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/dombreak.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/dombreak.c.o
.PHONY : src/techniques/dombreak.c.o

src/techniques/dombreak.i: src/techniques/dombreak.c.i
.PHONY : src/techniques/dombreak.i

# target to preprocess a source file
src/techniques/dombreak.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/dombreak.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/dombreak.c.i
.PHONY : src/techniques/dombreak.c.i

src/techniques/dombreak.s: src/techniques/dombreak.c.s
.PHONY : src/techniques/dombreak.s

# target to generate assembly for a file
src/techniques/dombreak.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/dombreak.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/dombreak.c.s
.PHONY : src/techniques/dombreak.c.s

src/techniques/domparser.o: src/techniques/domparser.c.o
.PHONY : src/techniques/domparser.o

# target to build an object file
src/techniques/domparser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/domparser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/domparser.c.o
.PHONY : src/techniques/domparser.c.o

src/techniques/domparser.i: src/techniques/domparser.c.i
.PHONY : src/techniques/domparser.i

# target to preprocess a source file
src/techniques/domparser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/domparser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/domparser.c.i
.PHONY : src/techniques/domparser.c.i

src/techniques/domparser.s: src/techniques/domparser.c.s
.PHONY : src/techniques/domparser.s

# target to generate assembly for a file
src/techniques/domparser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/domparser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/domparser.c.s
.PHONY : src/techniques/domparser.c.s

src/techniques/eventhand.o: src/techniques/eventhand.c.o
.PHONY : src/techniques/eventhand.o

# target to build an object file
src/techniques/eventhand.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/eventhand.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/eventhand.c.o
.PHONY : src/techniques/eventhand.c.o

src/techniques/eventhand.i: src/techniques/eventhand.c.i
.PHONY : src/techniques/eventhand.i

# target to preprocess a source file
src/techniques/eventhand.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/eventhand.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/eventhand.c.i
.PHONY : src/techniques/eventhand.c.i

src/techniques/eventhand.s: src/techniques/eventhand.c.s
.PHONY : src/techniques/eventhand.s

# target to generate assembly for a file
src/techniques/eventhand.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/eventhand.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/eventhand.c.s
.PHONY : src/techniques/eventhand.c.s

src/techniques/popup.o: src/techniques/popup.c.o
.PHONY : src/techniques/popup.o

# target to build an object file
src/techniques/popup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/popup.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/popup.c.o
.PHONY : src/techniques/popup.c.o

src/techniques/popup.i: src/techniques/popup.c.i
.PHONY : src/techniques/popup.i

# target to preprocess a source file
src/techniques/popup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/popup.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/popup.c.i
.PHONY : src/techniques/popup.c.i

src/techniques/popup.s: src/techniques/popup.c.s
.PHONY : src/techniques/popup.s

# target to generate assembly for a file
src/techniques/popup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/popup.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/popup.c.s
.PHONY : src/techniques/popup.c.s

src/techniques/scriptinj.o: src/techniques/scriptinj.c.o
.PHONY : src/techniques/scriptinj.o

# target to build an object file
src/techniques/scriptinj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/scriptinj.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/scriptinj.c.o
.PHONY : src/techniques/scriptinj.c.o

src/techniques/scriptinj.i: src/techniques/scriptinj.c.i
.PHONY : src/techniques/scriptinj.i

# target to preprocess a source file
src/techniques/scriptinj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/scriptinj.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/scriptinj.c.i
.PHONY : src/techniques/scriptinj.c.i

src/techniques/scriptinj.s: src/techniques/scriptinj.c.s
.PHONY : src/techniques/scriptinj.s

# target to generate assembly for a file
src/techniques/scriptinj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/scriptinj.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/scriptinj.c.s
.PHONY : src/techniques/scriptinj.c.s

src/techniques/svgmath.o: src/techniques/svgmath.c.o
.PHONY : src/techniques/svgmath.o

# target to build an object file
src/techniques/svgmath.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/svgmath.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/svgmath.c.o
.PHONY : src/techniques/svgmath.c.o

src/techniques/svgmath.i: src/techniques/svgmath.c.i
.PHONY : src/techniques/svgmath.i

# target to preprocess a source file
src/techniques/svgmath.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/svgmath.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/svgmath.c.i
.PHONY : src/techniques/svgmath.c.i

src/techniques/svgmath.s: src/techniques/svgmath.c.s
.PHONY : src/techniques/svgmath.s

# target to generate assembly for a file
src/techniques/svgmath.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/svgmath.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/svgmath.c.s
.PHONY : src/techniques/svgmath.c.s

src/techniques/taginj.o: src/techniques/taginj.c.o
.PHONY : src/techniques/taginj.o

# target to build an object file
src/techniques/taginj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/taginj.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/taginj.c.o
.PHONY : src/techniques/taginj.c.o

src/techniques/taginj.i: src/techniques/taginj.c.i
.PHONY : src/techniques/taginj.i

# target to preprocess a source file
src/techniques/taginj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/taginj.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/taginj.c.i
.PHONY : src/techniques/taginj.c.i

src/techniques/taginj.s: src/techniques/taginj.c.s
.PHONY : src/techniques/taginj.s

# target to generate assembly for a file
src/techniques/taginj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/taginj.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/taginj.c.s
.PHONY : src/techniques/taginj.c.s

src/techniques/uriinj.o: src/techniques/uriinj.c.o
.PHONY : src/techniques/uriinj.o

# target to build an object file
src/techniques/uriinj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/uriinj.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/uriinj.c.o
.PHONY : src/techniques/uriinj.c.o

src/techniques/uriinj.i: src/techniques/uriinj.c.i
.PHONY : src/techniques/uriinj.i

# target to preprocess a source file
src/techniques/uriinj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/uriinj.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/uriinj.c.i
.PHONY : src/techniques/uriinj.c.i

src/techniques/uriinj.s: src/techniques/uriinj.c.s
.PHONY : src/techniques/uriinj.s

# target to generate assembly for a file
src/techniques/uriinj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/uriinj.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/uriinj.c.s
.PHONY : src/techniques/uriinj.c.s

src/techniques/verify.o: src/techniques/verify.c.o
.PHONY : src/techniques/verify.o

# target to build an object file
src/techniques/verify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/verify.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/verify.c.o
.PHONY : src/techniques/verify.c.o

src/techniques/verify.i: src/techniques/verify.c.i
.PHONY : src/techniques/verify.i

# target to preprocess a source file
src/techniques/verify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/verify.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/verify.c.i
.PHONY : src/techniques/verify.c.i

src/techniques/verify.s: src/techniques/verify.c.s
.PHONY : src/techniques/verify.s

# target to generate assembly for a file
src/techniques/verify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/techniques/verify.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/src/techniques/verify.c.s
.PHONY : src/techniques/verify.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xssmap.dir/build.make CMakeFiles/xssmap.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... benchmark"
	@echo "... xssmap"
	@echo "... benchmark.o"
	@echo "... benchmark.i"
	@echo "... benchmark.s"
	@echo "... src/http.o"
	@echo "... src/http.i"
	@echo "... src/http.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/techniques/advanced.o"
	@echo "... src/techniques/advanced.i"
	@echo "... src/techniques/advanced.s"
	@echo "... src/techniques/attrbreak.o"
	@echo "... src/techniques/attrbreak.i"
	@echo "... src/techniques/attrbreak.s"
	@echo "... src/techniques/dombreak.o"
	@echo "... src/techniques/dombreak.i"
	@echo "... src/techniques/dombreak.s"
	@echo "... src/techniques/domparser.o"
	@echo "... src/techniques/domparser.i"
	@echo "... src/techniques/domparser.s"
	@echo "... src/techniques/eventhand.o"
	@echo "... src/techniques/eventhand.i"
	@echo "... src/techniques/eventhand.s"
	@echo "... src/techniques/popup.o"
	@echo "... src/techniques/popup.i"
	@echo "... src/techniques/popup.s"
	@echo "... src/techniques/scriptinj.o"
	@echo "... src/techniques/scriptinj.i"
	@echo "... src/techniques/scriptinj.s"
	@echo "... src/techniques/svgmath.o"
	@echo "... src/techniques/svgmath.i"
	@echo "... src/techniques/svgmath.s"
	@echo "... src/techniques/taginj.o"
	@echo "... src/techniques/taginj.i"
	@echo "... src/techniques/taginj.s"
	@echo "... src/techniques/uriinj.o"
	@echo "... src/techniques/uriinj.i"
	@echo "... src/techniques/uriinj.s"
	@echo "... src/techniques/verify.o"
	@echo "... src/techniques/verify.i"
	@echo "... src/techniques/verify.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

